name: Homebrew CI
on:
  push:
    branches: main
    paths: '**.rb'
  pull_request:
    paths:
    - Formula/*.rb
    - Casks/*.rb
    - cmd/*rb
    - lib/**.rb
  schedule:
  - cron: 0 5 * * * # 5AM daily

jobs:
  prejob:
    steps:
    - name: Pre job
      run: echo RAN pre job
  
  CI:
    uses: danielbayley/homebrew-pipeline/.github/workflows/action.yml@main
    secrets: inherit
    with:
      skip-install: cask,tokens
