name: Homebrew CI
on:
  push:
    branches: main
    paths: '**.rb'
  pull_request:
    paths:
    - Formula/*.rb
    - Casks/*.rb
    - cmd/*rb
    - lib/**.rb
  schedule:
  - cron: 0 5 * * * # 5AM daily

jobs:
  CI:
    uses: danielbayley/homebrew-pipeline/.github/workflows/action.yml@main
    secrets: inherit
    with:
      skip-install: cask,tokens
